/** PROBLEMA #5
 * UNA EMPRESA ALQUILA AUTOS DE TRES CLASES: PEQUEÑOS, MEDIANOS
 * Y GRANDES. LA TARIFA DE ALQUILER POR DIA ES: $50.000 EN EL
 * AUTO PEQUEÑO; $80.000 EN EL AUTO MEDIANO Y $110.000 EN EL
 * AUTO GRANDE. ADEMÀS, LA EMPRESA COBRA $1.500/KM RECORRIDO
 * EN EL AUTO PEQUEÑO, $2.300/KM RECORRIDO EN EL AUTO MEDIANO
 * Y $2.600/KM EN EL AUTO GRANDE. SI LA CANTIDAD DE KILOMETROS
 * RECORRIDOS POR EL AUTO SUPERA LOS 50 KM, SE LE AUMENTARÀ UN
 * 2.5% SOBRE EL MONTO A PAGAR POR EL CLIENTE. ELABORE UN
 * ALGORITMO QUE GENERE EL SIGUIENTE REPORTE:
 *
 * TAMAÑO DEL AUTO ALQUILADO:   XXX
 * TARIFA POR DÌA:              $$$
 * KILÒMETROS RECORRIDOS:       XXX
 * VALOR A PAGAR:               $$$
 */


package com.danielfernandoyepezvelez;

public class algoritmo05 {
}
